version: '3'
services:
  server:
    container_name: server
    restart: always
    build: .
    ports:
      - "3001:3001"
    links:
      - mongo
  client:
    container_name: client
    restart: always
    build: ./client
    ports:
      - "3000:3000"
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"